// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ymbvylycafyfjvwdzvtk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InltYnZ5bHljYWZ5Zmp2d2R6dnRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1OTkwNTksImV4cCI6MjA2ODE3NTA1OX0.GrOs7303SGDkfdbOSL-v0BR0B3XeDu0UyWAA8c-7A4w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});